language: python
sudo: false

cache: pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "2.7"
      env: TOXENV=docs

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "f7kRru3k45OrosvE32x0T2vI4J8dZdb/mA1ZzqJGBebrb5Rre8N4xTCUtg3CgZ3s3qS233knbIz2qZ7O4N5wjN0TJog2DrsDnB9ygMlMDw2r/2mvSv7PIo8GADRAzTs/lTyWkzVG93dTPYyIWlpdYMHU3ZUeZIK++Pjuo6Stnex0hhIqfK87SjQtUpdMt3ET12h9cons7dzsyanGOz+xMf6j9OMUVPmrfNxBQhI2XNGyhwQSZogltxgTJZT73FT0zbz6HgAUoTBu9bZAhgH1xGt0zqOmnNjdaJHysb2614hMQOWcqhnGaaCn3rgY1dZpzo7rLRDvYPl11df+BhJiomCbaMuan1KzYi6yz+WS6RHkjNSdc5mIEFFp8ulDEHtITRC7otUQmyboMAHIkhPMVsAGP7X3hV8YKAMV+pZEAn9e8wivWaOggmyAjPCqELSMHyowA0iRPmU+WhMlq6VKy+I5rOF+KpUCPOln9Kj9+90YMYzflZIxGINVVIAiZxgTnoYHr44j6fqnjYtluNFyyjx5iZMcjY1mUBLOQxVJpbYFD52hEdKKF+mrWPMjioHLQII4Wu3pj7b3e6OMArXPyQ3qoIf7aTQ36BbkwoXFxk4zg38Gmm4I6Zx3FXAd1FDH5CtxwNlF8AsaJrfxvAFMNIpu3xYDfLiebOVpEPUJINQ="
    api_key:
      secure: "ZD+3/yxYAokC/B3E4XLdSGMUj/5JDUguac29Qk1rTDJzRI9gYWwiRlwDaeYuz5tovLE6+F0l72MkzWSB+OUPev3L9746ezaTOFeV9/rdhOUZRXm0BL7Qo05pEtKpZMcv3v+b4VJCoBVYlOYjVOvgzGCuHDqheX7y9ie8mZWmP2kWQsQPm7s08vsuZWvGeZ4DjsQ1Czr2bQZkfebTBWtRIAMv5HgofMllRxm3PS5rFz3/lPpdyJ7P4GhuAhz/GwgzvyYeNcGVPjRcbW1ICyqsKJV7LEPqFWDX4h1jM15eo2PwmuFUIZYe8P78kdA+RW3IFHrTaT+CZCVSQuVMdVkm8PrMt1IXOwg0Ga5OnuasskbX1u8G58Kc+cguHi/6vlzeZFQi4zdhtGg0ZlLXfVY1Ag1lDoGblXHcxEtD4BefGThuyx0gBq5k+VP3U4sOgXlXHq2ZHd9bXgu4RUEFOI6uoCZLmkWihSbUD3UStRaDXBFZvsZbnYYAOdiC9mng9by2DrOuUbwIEq2qEFgYvLpx9Pp1DHN4Vr/GcKJa0LCF55cHG/wgdZ89ugky5xHpEsq4nujWhQV8tgzD9c9ZTyDXGAwXEkzIXMTjG3niQiBSMjmJPdFBIaETUOpJL0/9U38JcdX9liTDBxX68R3T6g3P4zertKZIEybwjXT/bnDcXy8="
branches:
  except:
    - "/^noci-.*$/"
